(cl:in-package frc_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FPGAVERSION-VAL
          FPGAVERSION
          FPGAREVISION-VAL
          FPGAREVISION
          FPGATIME-VAL
          FPGATIME
          USERBUTTON-VAL
          USERBUTTON
          ISSYSACTIVE-VAL
          ISSYSACTIVE
          ISBROWNEDOUT-VAL
          ISBROWNEDOUT
          INPUTVOLTAGE-VAL
          INPUTVOLTAGE
          INPUTCURRENT-VAL
          INPUTCURRENT
          VOLTAGE3V3-VAL
          VOLTAGE3V3
          CURRENT3V3-VAL
          CURRENT3V3
          ENABLED3V3-VAL
          ENABLED3V3
          FAULTCOUNT3V3-VAL
          FAULTCOUNT3V3
          VOLTAGE5V-VAL
          VOLTAGE5V
          CURRENT5V-VAL
          CURRENT5V
          ENABLED5V-VAL
          ENABLED5V
          FAULTCOUNT5V-VAL
          FAULTCOUNT5V
          VOLTAGE6V-VAL
          VOLTAGE6V
          CURRENT6V-VAL
          CURRENT6V
          ENABLED6V-VAL
          ENABLED6V
          FAULTCOUNT6V-VAL
          FAULTCOUNT6V
          CANDATA-VAL
          CANDATA
))