(cl:in-package frc_msgs-msg)
(cl:export '(PERCENTBUSUTILIZATION-VAL
          PERCENTBUSUTILIZATION
          BUSOFFCOUNT-VAL
          BUSOFFCOUNT
          TXFULLCOUNT-VAL
          TXFULLCOUNT
          RECEIVEERRORCOUNT-VAL
          RECEIVEERRORCOUNT
          TRANSMITERRORCOUNT-VAL
          TRANSMITERRORCOUNT
))