# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from frc_msgs/CubeState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CubeState(genpy.Message):
  _md5sum = "42388bfc6bfe50e21deb636904eb309b"
  _type = "frc_msgs/CubeState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool clamp
bool intake_high
bool intake_low
bool has_cube
"""
  __slots__ = ['clamp','intake_high','intake_low','has_cube']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       clamp,intake_high,intake_low,has_cube

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CubeState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.clamp is None:
        self.clamp = False
      if self.intake_high is None:
        self.intake_high = False
      if self.intake_low is None:
        self.intake_low = False
      if self.has_cube is None:
        self.has_cube = False
    else:
      self.clamp = False
      self.intake_high = False
      self.intake_low = False
      self.has_cube = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.clamp, _x.intake_high, _x.intake_low, _x.has_cube))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.clamp, _x.intake_high, _x.intake_low, _x.has_cube,) = _get_struct_4B().unpack(str[start:end])
      self.clamp = bool(self.clamp)
      self.intake_high = bool(self.intake_high)
      self.intake_low = bool(self.intake_low)
      self.has_cube = bool(self.has_cube)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.clamp, _x.intake_high, _x.intake_low, _x.has_cube))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.clamp, _x.intake_high, _x.intake_low, _x.has_cube,) = _get_struct_4B().unpack(str[start:end])
      self.clamp = bool(self.clamp)
      self.intake_high = bool(self.intake_high)
      self.intake_low = bool(self.intake_low)
      self.has_cube = bool(self.has_cube)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
