(cl:defpackage ros_control_boilerplate-srv
  (:use )
  (:export
   "LINEBREAKSENSORS"
   "<LINEBREAKSENSORS-REQUEST>"
   "LINEBREAKSENSORS-REQUEST"
   "<LINEBREAKSENSORS-RESPONSE>"
   "LINEBREAKSENSORS-RESPONSE"
   "SET_LIMIT_SWITCH"
   "<SET_LIMIT_SWITCH-REQUEST>"
   "SET_LIMIT_SWITCH-REQUEST"
   "<SET_LIMIT_SWITCH-RESPONSE>"
   "SET_LIMIT_SWITCH-RESPONSE"
  ))

